name: Debug2 build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/debug2.yml'
  pull_request:
    branches:
      - main
  watch:
      types: [started]
jobs:
  build:
    name: Debug2 build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.18.0-rc1
      - name: Init
        run: ./init.sh
      - name: Build
        run: ./build.sh
      - name: Upload libcore.aar
        uses: actions/upload-artifact@v1
        with:
          name: libcore
          path: ./libcore.aar
